### ISSUE TITLE
Overseer button not showing up on imdb

### ISSUE THREAD

**Issue by skynet01** [RemiRigal/Overseerr-Assistant#9] opened 2022-04-14 04:24 UTC
For some reason, the request button is not showing up on imdb site for me. Works everywhere else, is anyone experiencing this?

**Comment by RemiRigal** [comment] 2022-04-14 08:03
Hi @skynet01 ! Thank you for the issue, IMDb's page naming scheme has been updated and the extension was no longer able to know where to insert the button.
It should be fixed with version v1.1.1, feel free to reopen the issue if the problem is still there !

**Closed by RemiRigal** 2022-04-14 08:03 UTC
Labels: bug

**Comment by skynet01** [comment] 2022-04-14 19:22
You are amazing, thank you for such a fast fix, love the discovery integration as well!

**Comment by nononolimits** [comment] 2023-01-12 17:14
I have version 1.4.5, for me imdb isn't working at the moment (letterboxd does)
