### ISSUE TITLE
Using from subdirectory with reverse proxy

### ISSUE THREAD

**Issue by ronilaukkarinen** [RemiRigal/Overseerr-Assistant#7] opened 2022-02-28 20:02 UTC
Can't find documentation about this so asking in the issue. My overseerr is configured to run in subdirectory with reverse proxy, like https://xxxxx.xxxx.xxxx.xx/overseerr. For security reasons it cannot be run in subdomain, IP or public port, intead it uses 127.0.0.1:5055 which is available via vhost location block. However, settings won't allow this as I get "Unable to connect to Overseerr" every time.

Using "xxxxx.xxxx.xxxx.xx/overseerr/api/v1/auth/me" and API key provides "You are logged in" but IMDb still shows "Login to Overseerr":

![image](https://user-images.githubusercontent.com/1534150/156050528-9bfa056e-d309-4860-b96c-d5fdce37b81b.png)

**Comment by RemiRigal** [comment] 2022-04-14 13:41
Duplicate of #3.
This issue should be solved in v1.2.0.

**Closed by RemiRigal** 2022-04-14 13:41 UTC
